name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: cargo test --verbose
      
  Coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Coverage Tooling
      run: cargo install cargo-tarpaulin
    - name: Run Coverage
      run: cargo tarpaulin -v --out Xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
          fail_ci_if_error: true
